[versions]
spring-boot = "2.6.0"
dependency-management = "1.0.11.RELEASE"
testcontainers = "1.16.0"
lettuce = "6.1.5.RELEASE"

[plugins]
boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
dependency-management = { id = "io.spring.dependency-management", version.ref = "dependency-management" }

[libraries]
lettuce = { group = "io.lettuce", name = "lettuce-core", version.ref = "lettuce" }
