name: Default

on:
  - push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: success() || failure()
        with:
          api_key: ${{ secrets.THUNDRA_APIKEY }}
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - run: ./gradlew clean
      - run: ./gradlew build
      - name: Foresight test kit
        if: success() || failure()
        uses: runforesight/foresight-test-kit-action@v1
        with:
          api_key: ${{ secrets.THUNDRA_APIKEY }}
          test_format: JUNIT
          test_framework: JUNIT
          test_path: ./build/test-results/test
          coverage_format: JACOCO/XML
          coverage_path: ./build/reports/jacoco/test
